### ISSUE TITLE
hide debugShowCheckedModeBanner

### ISSUE THREAD

**Issue by Jyoshnarani** [YowFung/intro#6]
There is no code to hide debugShowCheckedModeBanner, while we are working on IntroStepTarget
![Screenshot 2023-07-13 172511](https://github.com/YowFung/intro/assets/58125446/23172ad1-9f1a-4491-91a7-195554879888)

**Comment by YowFung** [comment]
Hi @Jyoshnarani , you can try to set `debugShowCheckedModeBanner` attribute in `MaterialApp` Widget.

**Comment by Jyoshnarani** [comment]
Hello @YowFung 

I tried in this way,
but ModeBanner is still there when intro controller start.


void main() {
  return runApp(Intro(
    controller: IntroController(stepCount: 12),
    cardDecoration: IntroCardDecoration(
      tapBarrierToContinue: true,
      showPreviousButton: false,
      nextButtonStyle: ButtonStyle(
        backgroundColor:
        MaterialStateColor.resolveWith((states) => Colors.lightBlue),
        shape: MaterialStateProperty.resolveWith(
                (states) => const RoundedRectangleBorder()),
      ),
      closeButtonStyle: ButtonStyle(
        backgroundColor:
        MaterialStateColor.resolveWith((states) => Colors.lime),
        shape: MaterialStateProperty.resolveWith(
                (states) => const RoundedRectangleBorder()),
      ),
    ),
    topLayerBuilder: (context, controller) {
      return Padding(
        padding: const EdgeInsets.only(top: 20, left: 20),
        child: TextButton(
          onPressed: controller.close,
          style: ButtonStyle(
            foregroundColor:
            MaterialStateColor.resolveWith((states) => Colors.white70),
            backgroundColor:
            MaterialStateColor.resolveWith((states) => Colors.white24),
          ),
          child: const Text("Exit"),
        ),
      );
    },
    child: MaterialApp(
      **### debugShowCheckedModeBanner: false,**
      title: 'Intro Demo',
      routes: {
        "home": (context) => const HomePage(),
        "nested": (context) => const NestedDemoPage(),
      },
      initialRoute: "home",
    ),
  ));
}


![Screenshot_20230714_110801](https://github.com/YowFung/intro/assets/58125446/04a95549-ed8c-4020-89da-dfbe03489003)
![Screenshot_20230714_110810](https://github.com/YowFung/intro/assets/58125446/cb650608-3170-4ee4-a43b-f622e802cae2)

**Comment by YowFung** [comment]
Hi @Jyoshnarani, thanks for your feedback. It's indeed a problem but I have no good idea to optimize it because the `topLayerBuilder` is the parallel layer but not a child layer for your `MaterialApp` widget. You can try to use another `MaterialApp` in `topLayerBuilder` like this:

```dart
void main() {
  return runApp(Intro(
    ...
    topLayerBuilder: (context, controller) {
      return MaterialApp(  // The top layer widget for Intro.
        debugShowCheckedModeBanner: false,
        ...
      );
    },
    child: MaterialApp(   // Your main application widget.
        debugShowCheckedModeBanner: false,
        ...
    ),
  ));
}

```

**Comment by Jyoshnarani** [comment]
Hello @YowFung .
Thanks for your references.
This one is good solution. 
I will try this.
