### ISSUE TITLE
Can not update Highlight widget

### ISSUE THREAD

**Issue by fatihyuksell** [YowFung/intro#8]
Adding only the TextSpan widget to cardContents, which is used for the description text about the focused part of the screen, limits the usage area.

**Comment by ogedaysunar** [comment]
any updates??

**Comment by enesctn** [comment]
I have some issue, any update?

**Comment by uygar** [comment]
any updates??

**Comment by YowFung** [comment]
Hi, @fatihyuksell @ogedaysunar @enesctn @uygar 
Can you provide some more detailed informations? Such as error logs, screenshots, demonstration videos, etc.

**Comment by fatihyuksell** [comment]
<img width="586" alt="Screenshot 2023-12-13 at 13 38 17" src="https://github.com/YowFung/intro/assets/61410293/0b0bdac0-68c4-4dcd-9f2f-8c49368f2f06">

IntroStepTarget has the cardContents parameter to give the focused area description. The fact that this parameter only takes textSpan creates a limitation in showing the description of the focused area. @YowFung

**Comment by YowFung** [comment]
That is the default way to use `IntroStepTarget`. If you want to customize your focused area, you can use `IntroStepTarget.custom` like this:

```dart
IntroStepTarget.custom(
  step: step,
  controller: controller,
  highlightDecoration: IntroHighlightDecoration(...),
  cardDecoration: IntroCardDecoration(...),
  cardBuilder: (context, param, decoration) {
    // TODO: Return your customized card widget...
  },
  child: child,
);
```

Refer to the `example` program for more detailed demonstration code. @fatihyuksell
